// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_OPwhaZlt8AlUnlAi7JWsk5QVqXBQUA',
    appId: '1:1085856428414:android:26a8c8e7ae2fa51f8bc32f',
    messagingSenderId: '1085856428414',
    projectId: 'e-some',
    storageBucket: 'e-some.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZk7yVHNqxncQwff_bTdK75GmUDWh-wo',
    appId: '1:1085856428414:ios:79bf029f3c92dab48bc32f',
    messagingSenderId: '1085856428414',
    projectId: 'e-some',
    storageBucket: 'e-some.appspot.com',
    androidClientId: '1085856428414-ct98t00dh9th1hiq1bvvj1nurnma7s58.apps.googleusercontent.com',
    iosClientId: '1085856428414-fd2kpv3740n0f3ocvtetk05s5hl5ah02.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
